name: Artifact

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
    branches: [master]

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Get Info
        run: |
          echo "version=$(grep -Eo '[0-9]+(\.[0-9]+)+' CHANGELOG.md | head -n 1)" >> $GITHUB_OUTPUT
        id: info
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Dependencies
        run: | 
          python3 -m pip install --upgrade build
          pip install -r requirements.txt
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          git submodule update --init --recursive
          rm -rf ./.git/
          rm .gitignore
          rm .gitmodules
          python3 -m build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: onlyoffice.plone-${{ steps.info.outputs.version }}
          path: ${{ github.workspace }}/dist/onlyoffice.plone-${{ steps.info.outputs.version }}.tar.gz